### ISSUE TITLE
d[1] for tipHtml incorrect in non-stacked series

### ISSUE THREAD

**Issue by randalpinto** [redsift/d3-rs-lines#2]
See: http://codepen.io/rpinto/pen/jrWxrg

Hovering over 100 outputs:
"tipHtml: " [1451606400000, [0, 100]] 0 0

Expected:
"tipHtml: " [1451606400000, [100, 0]] 0 0

**Comment by rahulpowar** [comment]
Should be fixed in v0.3.0.

The change makes non stacked bars return a non nested array e.g. in the sample above "tipHtml: " [1451606400000, 100] 0 0

**Comment by randalpinto** [comment]
Side effect of this fix is that the default tip no longer works. If you don't customize the tipHtml it will present something like "Mar, undefined"

**Comment by rahulpowar** [comment]
Fixed in 0.3.1

**Comment by randalpinto** [comment]
Stacked series tip now present "undefined" when the value is 0. i.e.: {l: 1400000, v: [0,0]}

**Comment by rahulpowar** [comment]
Fixed in 0.3.2
