### ISSUE TITLE
Font loading is interfering with fonts on an HTML page

### ISSUE THREAD

**Issue by randalpinto** [redsift/d3-rs-lines#4]
The loading of the fonts required by the chart is interfering with the fonts on the page. Allow option to load chart without loading fonts?

**Comment by rahulpowar** [comment]
Added `importFonts(bool)` to the chart. true by default. Set to false when using it with other imports that are not the reusable charts. Make sure Source+Code+Pro:300,500 and Raleway:400,500 are included in the manually imported bundle.
